	cout<<"----------------------------------------------------------------------------"<<endl;
    cout<<"| NO |     Kota    | Tarif Dakota Cargo 20kg Pertama | Tarif Kg Berikutnya |"<<endl;
	cout<<"----------------------------------------------------------------------------"<<endl;
	cout<<"| 1  |Bandung      | 24.000                          | 2.900               |"<<endl;
	cout<<"| 2  |Banyuwangi   | 89.000                          | 4.450               |"<<endl;
	cout<<"| 3  |Bekasi       | 53.000                          | 2.650               |"<<endl;
	cout<<"| 4  |Cianjur      | 28.000                          | 1.400               |"<<endl;
	cout<<"| 5  |Cirebon      | 58.000                          | 2.900               |"<<endl;
	cout<<"| 6  |Denpasar     | 67.000                          | 3.350               |"<<endl;
	cout<<"| 7  |Jakarta      | 29.000                          | 1.450               |"<<endl;
	cout<<"| 8  |Jember       | 61.000                          | 3.050               |"<<endl;
	cout<<"| 9  |Jombang      | 78.000                          | 3.900               |"<<endl;
	cout<<"| 10 |Kediri       | 80.000                          | 4.000               |"<<endl;
	cout<<"----------------------------------------------------------------------------"<<endl;